### ISSUE TITLE
Debian 8 not supported

### ISSUE THREAD

**Issue by bogdanr** [saltstack-formulas/nginx-formula#109]
Debian 8 uses systemd so this error would get fired up:

```
          ID: nginx
    Function: service.running
      Result: False
     Comment: One or more requisite failed: nginx.upstart.nginx-logger-access, nginx.upstart.nginx-logger-error
     Started: 
    Duration: 
     Changes: 
```

I am not sure if adding Debian 8 support or rewriting the install formula to make it simpler would be the better option.
