### ISSUE TITLE
How, I can using condition in nginx-ng

### ISSUE THREAD

**Issue by fessoga5** [saltstack-formulas/nginx-formula#110]
I have:

> location = /robots.txt {
>         set $subdomain_robots "robots.txt";
>         if ($host ~\* ^((?!(www|test))[^.]+).(.*)) {
>              set $subdomain_robots robots_$1.txt;
>         }

How?

**Comment by hackel** [comment]
Just convert it to YAML...
```yaml
- location = /robots.txt:
    - set $subdomain_robots "robots.txt";
    - if ($host ~* ^((?!(www|test))[^.]+).(.*)):
        - set $subdomain_robots robots_$1.txt;
```

**Comment by fessoga5** [comment]
Hello! Don't work!
`location = /robots.txt set $subdomain_robots`

**Comment by fessoga5** [comment]
Don't work ! =(

**Comment by blaketmiller** [comment]
Totally works for me:

```
# snippet from my config
...
    config:
      - server:
        - listen: 80
        - server_name: example.com
        - location /:
          - if ($example_variable = ''):
            - rewrite: ^/$ http://$http_host/web/index.html
...
```

**Comment by EvaSDK** [comment]
Maybe because the `:` where missing from @hackel's sample ?

**Comment by dseira** [comment]
As @EvaSDK commented, it is missing the ``:`` after the ``set`` keyword. The full correct example is:

```
config:
    - server:
        - server_name: localhost
        - listen: 80
        - location = /robots.txt:
            - set: $subdomain_robots "robots.txt"
            - if ($host ~* ^((?!(www|test))[^.]+).(.*)):
                - set: $subdomain_robots robots_$1.txt
```
Now, you can also use the ``source_path`` option just to indicate the location of the file (instead of having to format the config to yaml) and salt just upload the file to the proper folder:
```
example.com:
    config:
        source_path: salt://path-to-file/example.com
```
