### ISSUE TITLE
[Request] Allow using strings for vhost config blocks

### ISSUE THREAD

**Issue by hackel** [saltstack-formulas/nginx-formula#111]
It seems like an unnecessary nuisance to have to convert config sections from the nginx config file format to YAML.  It would be great if there was a way to simply use a config block directly.  The closest I've come to that is this, but it leaves an extra ; at the end if the block, which nginx can't handle.

``` yaml
nginx:
  ng:
    vhosts:
      managed:
        default:
          config:
            - server:
              - location /:
                - '': |
                    proxy_set_header ...;
                    if (something) {
                        etc...;
                    }
                    charset utf-8
```

The way I got around the limitation was to add the redundant charset line at the end, but leave off the semicolon.
