### ISSUE TITLE
No matching sls found for nginx.ng.install

### ISSUE THREAD

**Issue by devster31** [saltstack-formulas/nginx-formula#121]
I added the formula and tried to install `nginx-full` with a pillar like:

```
nginx:
  ng:
    lookup:
      package: nginx-full
```

I used this line:

```
salt 'role:web' state.apply nginx.ng.install
```

but I got:

```
web:
    Data failed to compile:
----------
    No matching sls found for 'nginx.ng.install' in env 'base'
```
