### ISSUE TITLE
Sorting keys breaks nginx.conf

### ISSUE THREAD

**Issue by devster31** [saltstack-formulas/nginx-formula#122]
Using a pillar like:

```
nginx:
  ng:
    server:
      config:
        http:
          log_format: "main '$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\"'" \"$http_user_agent\" \"$http_x_forwarded_for\""
          access_log: logs/access.log main
```

with the state `nginx.ng.config` produces an invalid `nginx.conf` since the `access_log` directive is put higher in the config and the log_format isn't defined yet.
[Nginx HTTP Log Module Reference](http://nginx.org/en/docs/http/ngx_http_log_module.html)
