### ISSUE TITLE
Define arbitrary config files in the style of the vhost data structure.

### ISSUE THREAD

**Issue by nicksloan** [saltstack-formulas/nginx-formula#133]
It would be handy to allow for additional config files to be defined in the same manner as a vhost file. Splitting complex configuration out into other files can do wonders to simplify complex config files (and pillars, for that matter).

**Comment by genuss** [comment]
I personally use disabled servers and include them via ``include sites-available/site``.
Does anyone have better solution?

**Comment by aboe76** [comment]
@nicksloan what about something like this:

```
nginx:
  ng:
    servers:
      # need some extra file.managed options if dir doesn't exist.
      managed_opts:
        makedirs: True 
      managed:
        php.conf:
          enabled: False
          available_dir: /etc/nginx/snippets
          config:
            # test snippets
            - location ~ \.php$:
              - try_files:
                - $uri =404
              - fastcgi_split_path_info: ^(.+\.php)(/.+)$
              - fastcgi_pass: unix://run/www-sockets/php-main.sock
              - fastcgi_index: index.php
````
