### ISSUE TITLE
"location" has no opening "{"

### ISSUE THREAD

**Issue by mmcculloch** [saltstack-formulas/nginx-formula#144]
Given the configuration at the bottom, the default configuration seems to omit the opening brace in the location param.

```
server {
    server_name localhost;
    listen 80 default_server;
    root /var/apps/test/current;
    location /.well-known allow all
}
```

I've tried combining them into one config, but no matter what it fails to write location in the correct format.

```
nginx:
    ng:
        servers:
            managed:
                default:
                    enabled: True
                    config:
                        - server:
                            - server_name: localhost
                            - listen:
                                - 80
                                - default_server
                            - root: /var/apps/test/current
                            - location /.well-known:
                                - allow all
                watsonhere:
                    enabled: True
                    config:
                        - server:
                            - server_name: localhost
                            - ssl_certificate: /etc/letsencrypt/live/api.test.com/fullchain.pem
                            - ssl_certificate_key: /etc/letsencrypt/live/api.test.com/privkey.pem
                            - listen:
                                - 443
                                - ssl
                            - root: /var/apps/test/current
                            - location /:
                                - proxy_pass: http://localhost:3010
                                - proxy_http_version: 1.1
                                - proxy_set_header: Upgrade $http_upgrade
                                - proxy_set_header: Connection 'upgrade'
                                - proxy_set_header: Host $host
                                - proxy_cache_bypass: $http_upgrade
```
