### ISSUE TITLE
Default site conflicts with configured site

### ISSUE THREAD

**Issue by waynegemmell** [saltstack-formulas/nginx-formula#147]
Hi

I've configured my own site declaration as per below. When I run the formula the first time then nginx won't start because of a conflict in default_server. This is because the 'default' site is created. When I run the formula the second time then the 'default' site is removed  and everything works perfectly. Is this a bug? Should I just use 'default' as the site file name? 

```
    servers:

      # vhost declarations
      # vhosts will default to being placed in vhost_available
      managed:
        site1: # relative pathname of the vhost file
          # may be True, False, or None where True is enabled, False, disabled, and None indicates no action
          enabled: True
          config:
            - server:
              - root:
                - `/var/www/site1`

              - listen: 
                - 80
                - default_server
```
