### ISSUE TITLE
add mutltiple allow/deny directives

### ISSUE THREAD

**Issue by toanju** [saltstack-formulas/nginx-formula#155]
What is the correct way to add multiple allow/deny directives like

```
location / {
    deny  192.168.1.1;
    allow 192.168.1.0/24;
    allow 10.1.1.0/16;
    allow 2001:0db8::/32;
    deny  all;
}
```
for more details see http://nginx.org/en/docs/http/ngx_http_access_module.html

currently I am using nginx.ng

**Comment by aboe76** [comment]
I would do it in two files:
```
nginx:
  ng:
    servers:
      managed:
        allow_hosts.conf:
          enabled: false
          available_dir: /etc/nginx
          config:
            - geo $not_allowed:
              - default: 1
              - 192.168.1.1: 1
              - 192.168.1.0/24: 0
              - 10.1.1.0/16: 0
              - '2001:0db8::/321: 0
```
```
second part:
```
location \:
  if ($not_allowed):
    - deny: all
```
that way you can easily add more ip addresses without messing up the main part.
