### ISSUE TITLE
in server blocks the autoindex property is set to True instead of on

### ISSUE THREAD

**Issue by cmurczek** [saltstack-formulas/nginx-formula#170]
Im using the following top file with Salt 2017.7.1 and nginx-formula as of today (Sept. 22, 2017):
```yaml
base:
    'roles: webserver':
        - match: grain
        - nginx.servers
        - nginx.config
```
with this pillar:
```yaml
nginx:
    ng:
        install_from_repo: False
        install_from_phusionpassenger: False
        install_from_ppa: False
        service:
            enable: True
        server:
            config:
                http:
                    include:
                        - /etc/nginx/sites-enabled/*
        servers:
            managed:
                web1:
                    enabled: True
                    config:
                        - server:
                            - server_name: web1.example.com
                            - listen: 9090
                            - access_log: /var/log/nginx/web1_access.log
                            - error_log: /var/log/nginx/web1_error.log
                            - location /:
                                - root: /var/www/web1
                                - index: index.html
                                - autoindex: on
                web2:
                    enabled: True
                    config:
                        - server:
                            - server_name: web2.example.com
                            - listen: 9091
                            - access_log: /var/log/nginx/web2_access.log
                            - error_log: /var/log/nginx/web2_error.log
                            - location /:
                                - root: /var/www/web2
                                - index: index.html
                                - autoindex: on
```
In the server block files created by the formula the `autoindex` property is set to `True` instead of `on`, causing nginx failing to reload.
