### ISSUE TITLE
nginx.ng - generated server configuration file is not included

### ISSUE THREAD

**Issue by Poil** [saltstack-formulas/nginx-formula#188]
Hi,

On EL7, using nginx repository, with this simple test, this formula generate this configuration file `/etc/nginx/conf.d/moten`
But nginx.conf only include `*.conf̀ in `conf.d`

```
    include conf.d/*.conf;
    include sites-enabled/*;
```

Pillar :
```
nginx:
  ng:
    install_from_repo: true
    servers:
      managed:
        molten:
          enabled: True
          config:
            - server:
              - server_name: molten
              - listen:
                - 80
                - default_server
              - index:
                - index.html
              - location /:
                - root: /opt/molten
```
