### ISSUE TITLE
Enable site and add watch to nginx.ng service

### ISSUE THREAD

**Issue by bebosudo** [saltstack-formulas/nginx-formula#191]
Hi,
I'm pretty new to salt and salt formulas, and I still have some doubts on them.

I'm trying to use `nginx.ng` to install and configure nginx on a minion to serve packages as a local repository.
I wrote a simple pillar that overrides centos vhost directory defaults (`/etc/nginx/sites-{available,enabled}`) and provides a vhost that serves some files. The vhost config file is parsed and generated correctly, and placed in `nginx:ng:lookup:server_available`.

First question: how should I enable this site?
At the moment I came up with a specific state (parsed output):
```
/etc/nginx/site-enabled/test_site:
  file.symlink:
    - target: /etc/nginx/site-enabled/test_site
    - require:
      - file: /etc/nginx/site-available/test_site
```
is this correct? Isn't there an automatic way to enable a site?

Second question: how should I properly setup a watch requirement, so that when any change is made to the `nginx.ng` package, the service `nginx.ng.service` is restarted?

Thanks guys!
