### ISSUE TITLE
Config stream

### ISSUE THREAD

**Issue by robertzd** [saltstack-formulas/nginx-formula#193]
Hi,
I might misunderstand something but trying to configure the stream module (ngx_stream_core_module - https://nginx.org/en/docs/stream/ngx_stream_core_module.html).

Pillar:
```
nginx:
  ng:
    server:
      config:
        stream:
          upstream lb-1000:
            - server:
              - hostname1.example.com:1000
              - hostname2.example.com:1000
          server:
            - listen: 1000
            - proxy_pass: lb-1000
```

and it's produce this config in nginx.conf:
```
stream {

    server {
        listen 1000;
    }
    server {
        proxy_pass lb-1000;
    }

    upstream lb-1000 {

        server hostname1.example.com:1000;
        server hostname2.example.com:1000;
    }
}

```

and this is ofc not a valid config, in my mind (might be the problem here :-P ) it should look something like this:
```
stream {
    server {
        listen 1000;
        proxy_pass lb-1000;
    }
    upstream lb-1000 {
        server hostname1.example.com:1000;
        server hostname2.example.com:1000;
    }
}
```

Is it the formula that's not supporting stream or any bug to how things are "compiled" in the conf file?

```
# salt --version
salt 2018.3.0 (Oxygen)
```

Thanks a bunch!
