### ISSUE TITLE
Removing default site complicated

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/nginx-formula#221]
To remove `default` vhost in `nginx.ng` you need to configure with

```
  nginx:
    ng:
      servers:
        managed:
          default:
            available: false
            deleted: true
            config: {}
            enabled: false
```
_(important part are 4 k/v below)_
It should be possible to only need
```
[...]
          default:
            enabled: false
```
