### ISSUE TITLE
tests: on v2018-3-py2-opensuse-423 a declared vhost/site is not enabled

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/nginx-formula#224]
With the following pillar to declare a `mysite` site:
 ```
nginx:
  ng:
    servers:
      managed:
        mysite:
          enabled: True
          config:
            - server:
              - server_name: localhost
              - listen:
                - '80 default_server'
              - index: 'index.html index.htm'
              - location ~ .htm:
                - try_files: '$uri $uri/ =404'
              - include: 'snippets/letsencrypt.conf'
```
this site is not enabled on OpenSuse42, while it is on other OS. 

File is created in `/etc/nginx/sites-available` but not in `/etc/nginx/sites-enabled`.

See https://travis-ci.com/saltstack-formulas/nginx-formula/jobs/192697675 and #222 for details
