### ISSUE TITLE
/etc/nginx/ssl not created before dhparam is generated

### ISSUE THREAD

**Issue by prometheanfire** [saltstack-formulas/nginx-formula#241]
Just likely needs a require on the dir

**Comment by djolitsu** [comment]
Hi, 
I have the same problem here.
I just add these pillars :
```
nginx:
  dh_param:
    'dhparam.pem':
        keysize: 4096
```
Salt version: 2019.2.0
Error message: Desired working directory "/etc/nginx/ssl" is not available
