### ISSUE TITLE
Create better namespacing for pillar items

### ISSUE THREAD

**Issue by kmshultz** [saltstack-formulas/nginx-formula#25]
For better clarity, I think the pillar items for this formula need a few namespacing enhancements:
- anything thing that finds its way into `/etc/nginx/nginx.conf` would go under `nginx:conf` instead of just `nginx`. Items directly below `nginx` would be reserved for special values that affect the behavior of the formula, e.g. `use_upstart`. For example, this:

```
nginx:
  install_from_source: False
  use_upstart: False
  user: www-data
  events:
    worker_connections: 5000
```

would become:

```
nginx:
  install_from_source: False
  use_upstart: False
  config:
    user: www-data
    events:
      worker_connections: 5000
```
- Items in the events block of nginx.conf are namespaced separately from global nginx configuration items, but items in the http block are not. For example, this:

```
nginx:
  keepalive_timeout: 15
```

should be (not taking into account the `config` namespace from the first example):

```
nginx:
  http:  
    keepalive_timeout: 15
```

Many of the saltstack-formulas could use more standard namespacing, but it's especially useful in this formula as the number of supported pillar items grow (also because I happen to be working on this one :))

I would have submitted this as a pull request, but wanted to get opinions before presuming to change the structure. Thoughts, anyone?
