### ISSUE TITLE
nginx.users does not take effect for htauth file is not exist.

### ISSUE THREAD

**Issue by heww** [saltstack-formulas/nginx-formula#70]
In salt-contrib's module basicauth.py https://github.com/saltstack/salt-contrib/blob/master/modules/basicauth.py#L23-L26

```python
"""
...
The htpasswd file must exist in order to successfully 
add and delete users. You can create a new empty file as follows::

    touch /etc/.htpasswd
...
"""
```

It will be ok, when create file after htpasswd installed and before basicauth.adduser.
``` yaml
htauth:
  file.managed:
    - name: {{ htauth }}
```
