### ISSUE TITLE
rewrite log value in pillar for nginx.conf is changed from 'off' to 'False'

### ISSUE THREAD

**Issue by MarkMarine** [saltstack-formulas/nginx-formula#71]
Here is the part of the pillar data that generates the nginx.conf

```
    server:
      opts: {} # this partially exposes file.managed parameters as they relate to the main nginx.conf file

      # nginx.conf (main server) declarations
      # dictionaries map to blocks {} and lists cause the same declaration to repeat with different values
      config:
        user: www-data
        worker_processes: 8
        worker_rlimit_nofile: 999999
        pid: /run/nginx.pid
        events:
          worker_connections: 900000
          use: epoll
        http:
          sendfile: 'on'
          tcp_nopush: on
          tcp_nodelay: on
          keepalive_timeout: 30
          types_hash_max_size: 2048
          keepalive_requests: 100000
          include:
            - /etc/nginx/mime.types
            - /etc/nginx/conf.d/*.conf
            - /etc/nginx/sites-enabled/*
          default_type: application/octet-stream
          access_log: /var/log/nginx/access.log
          rewrite_log: off
          error_log: /var/log/nginx/error.log
```

Here is the log error message:

```
2015/01/22 00:24:16 [emerg] 17239#0: invalid value "False" in "rewrite_log" directive, it must be "on" or "off" in /etc/nginx/nginx.conf:24
```

This is the compiled config file:

```
# Default nginx server configuration
#
# **** DO NOT EDIT THIS FILE ****
#
# This file is managed by Salt.


events {
    use epoll;
    worker_connections 900000;
}
http {
    access_log /var/log/nginx/access.log;
    default_type application/octet-stream;
    error_log /var/log/nginx/error.log;
    gzip off;
    gzip_disable "msie6";

    include /etc/nginx/mime.types;
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
    keepalive_requests 100000;
    keepalive_timeout 30;
    rewrite_log False;
    sendfile on;
    tcp_nodelay True;
    tcp_nopush True;
    types_hash_max_size 2048;
}
pid /run/nginx.pid;
user www-data;
worker_processes 8;
worker_rlimit_nofile 999999;
```
