### ISSUE TITLE
daemon: no breaks jessie + systemd

### ISSUE THREAD

**Issue by bersace** [saltstack-formulas/nginx-formula#77]
Hi,

On debian jessie with systemd, service reloading fails with :

```
nginx: [emerg] "daemon" directive is duplicate in /etc/nginx/nginx.conf
```

Looks like `daemon: no` directive in `/etc/nginx/nginx.conf` is useful for upstart or sysvinit files that do not call properly nginx.

Systemd unit file already setup daemon directive and nginx does not allow duplicate of this directive.

Here is a workaround i use :

``` yaml
{% if grains['oscodename'] == 'jessie' -%}
patch_nginx_conf:
  file.comment:
    - name: /etc/nginx/nginx.conf
    - regex: daemon
    - char: '# '

extend:
  nginx:
    pkg:
      - require:
        - file: patch_nginx_conf
{%- endif %}
```

See also :  https://github.com/jdauphant/ansible-role-nginx/issues/38
